/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedWWsIdRouteRouteImport } from './routes/_authenticated/w/$wsId/route'
import { Route as AuthenticatedWWsIdIndexRouteImport } from './routes/_authenticated/w/$wsId/index'
import { Route as AuthenticatedWWsIdSettingsRouteImport } from './routes/_authenticated/w/$wsId/settings'
import { Route as AuthenticatedWWsIdPProjectIdRouteRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/route'
import { Route as AuthenticatedWWsIdPProjectIdIndexRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/index'
import { Route as AuthenticatedWWsIdPProjectIdTaxonomyRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/taxonomy'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWWsIdRouteRoute = AuthenticatedWWsIdRouteRouteImport.update({
  id: '/w/$wsId',
  path: '/w/$wsId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWWsIdIndexRoute = AuthenticatedWWsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedWWsIdRouteRoute,
} as any)
const AuthenticatedWWsIdSettingsRoute =
  AuthenticatedWWsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWsIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdRouteRoute =
  AuthenticatedWWsIdPProjectIdRouteRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => AuthenticatedWWsIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdIndexRoute =
  AuthenticatedWWsIdPProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdTaxonomyRoute =
  AuthenticatedWWsIdPProjectIdTaxonomyRouteImport.update({
    id: '/taxonomy',
    path: '/taxonomy',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdQaStageSlugRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRouteImport.update({
    id: '/qa/$stageSlug',
    path: '/qa/$stageSlug',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/w/$wsId': typeof AuthenticatedWWsIdRouteRouteWithChildren
  '/w/$wsId/settings': typeof AuthenticatedWWsIdSettingsRoute
  '/w/$wsId/': typeof AuthenticatedWWsIdIndexRoute
  '/w/$wsId/p/$projectId': typeof AuthenticatedWWsIdPProjectIdRouteRouteWithChildren
  '/w/$wsId/p/$projectId/taxonomy': typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  '/w/$wsId/p/$projectId/': typeof AuthenticatedWWsIdPProjectIdIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/w/$wsId/settings': typeof AuthenticatedWWsIdSettingsRoute
  '/w/$wsId': typeof AuthenticatedWWsIdIndexRoute
  '/w/$wsId/p/$projectId/taxonomy': typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  '/w/$wsId/p/$projectId': typeof AuthenticatedWWsIdPProjectIdIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/w/$wsId': typeof AuthenticatedWWsIdRouteRouteWithChildren
  '/_authenticated/w/$wsId/settings': typeof AuthenticatedWWsIdSettingsRoute
  '/_authenticated/w/$wsId/': typeof AuthenticatedWWsIdIndexRoute
  '/_authenticated/w/$wsId/p/$projectId': typeof AuthenticatedWWsIdPProjectIdRouteRouteWithChildren
  '/_authenticated/w/$wsId/p/$projectId/taxonomy': typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  '/_authenticated/w/$wsId/p/$projectId/': typeof AuthenticatedWWsIdPProjectIdIndexRoute
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/workspaces'
    | '/w/$wsId'
    | '/w/$wsId/settings'
    | '/w/$wsId/'
    | '/w/$wsId/p/$projectId'
    | '/w/$wsId/p/$projectId/taxonomy'
    | '/w/$wsId/p/$projectId/'
    | '/w/$wsId/p/$projectId/qa/$stageSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/workspaces'
    | '/w/$wsId/settings'
    | '/w/$wsId'
    | '/w/$wsId/p/$projectId/taxonomy'
    | '/w/$wsId/p/$projectId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/workspaces'
    | '/_authenticated/w/$wsId'
    | '/_authenticated/w/$wsId/settings'
    | '/_authenticated/w/$wsId/'
    | '/_authenticated/w/$wsId/p/$projectId'
    | '/_authenticated/w/$wsId/p/$projectId/taxonomy'
    | '/_authenticated/w/$wsId/p/$projectId/'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/w/$wsId': {
      id: '/_authenticated/w/$wsId'
      path: '/w/$wsId'
      fullPath: '/w/$wsId'
      preLoaderRoute: typeof AuthenticatedWWsIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/w/$wsId/': {
      id: '/_authenticated/w/$wsId/'
      path: '/'
      fullPath: '/w/$wsId/'
      preLoaderRoute: typeof AuthenticatedWWsIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdRouteRoute
    }
    '/_authenticated/w/$wsId/settings': {
      id: '/_authenticated/w/$wsId/settings'
      path: '/settings'
      fullPath: '/w/$wsId/settings'
      preLoaderRoute: typeof AuthenticatedWWsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWWsIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId': {
      id: '/_authenticated/w/$wsId/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/w/$wsId/p/$projectId'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedWWsIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/': {
      id: '/_authenticated/w/$wsId/p/$projectId/'
      path: '/'
      fullPath: '/w/$wsId/p/$projectId/'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/taxonomy': {
      id: '/_authenticated/w/$wsId/p/$projectId/taxonomy'
      path: '/taxonomy'
      fullPath: '/w/$wsId/p/$projectId/taxonomy'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdTaxonomyRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug'
      path: '/qa/$stageSlug'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
  }
}

interface AuthenticatedWWsIdPProjectIdRouteRouteChildren {
  AuthenticatedWWsIdPProjectIdTaxonomyRoute: typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  AuthenticatedWWsIdPProjectIdIndexRoute: typeof AuthenticatedWWsIdPProjectIdIndexRoute
  AuthenticatedWWsIdPProjectIdQaStageSlugRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoute
}

const AuthenticatedWWsIdPProjectIdRouteRouteChildren: AuthenticatedWWsIdPProjectIdRouteRouteChildren =
  {
    AuthenticatedWWsIdPProjectIdTaxonomyRoute:
      AuthenticatedWWsIdPProjectIdTaxonomyRoute,
    AuthenticatedWWsIdPProjectIdIndexRoute:
      AuthenticatedWWsIdPProjectIdIndexRoute,
    AuthenticatedWWsIdPProjectIdQaStageSlugRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRoute,
  }

const AuthenticatedWWsIdPProjectIdRouteRouteWithChildren =
  AuthenticatedWWsIdPProjectIdRouteRoute._addFileChildren(
    AuthenticatedWWsIdPProjectIdRouteRouteChildren,
  )

interface AuthenticatedWWsIdRouteRouteChildren {
  AuthenticatedWWsIdSettingsRoute: typeof AuthenticatedWWsIdSettingsRoute
  AuthenticatedWWsIdIndexRoute: typeof AuthenticatedWWsIdIndexRoute
  AuthenticatedWWsIdPProjectIdRouteRoute: typeof AuthenticatedWWsIdPProjectIdRouteRouteWithChildren
}

const AuthenticatedWWsIdRouteRouteChildren: AuthenticatedWWsIdRouteRouteChildren =
  {
    AuthenticatedWWsIdSettingsRoute: AuthenticatedWWsIdSettingsRoute,
    AuthenticatedWWsIdIndexRoute: AuthenticatedWWsIdIndexRoute,
    AuthenticatedWWsIdPProjectIdRouteRoute:
      AuthenticatedWWsIdPProjectIdRouteRouteWithChildren,
  }

const AuthenticatedWWsIdRouteRouteWithChildren =
  AuthenticatedWWsIdRouteRoute._addFileChildren(
    AuthenticatedWWsIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedWWsIdRouteRoute: typeof AuthenticatedWWsIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedWWsIdRouteRoute: AuthenticatedWWsIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
