/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AuthenticatedWWsIdRouteRouteImport } from './routes/_authenticated/w/$wsId/route'
import { Route as AuthenticatedWWsIdIndexRouteImport } from './routes/_authenticated/w/$wsId/index'
import { Route as AuthenticatedWWsIdSettingsRouteImport } from './routes/_authenticated/w/$wsId/settings'
import { Route as AuthenticatedWWsIdPProjectIdRouteRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/route'
import { Route as AuthenticatedWWsIdPProjectIdIndexRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/index'
import { Route as AuthenticatedWWsIdPProjectIdIssuesRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/issues'
import { Route as AuthenticatedWWsIdPProjectIdTaxonomyRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/taxonomy'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/route'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugIndexRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/index'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/route'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/index'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/route'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/index'
import { Route as AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRouteImport } from './routes/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWWsIdRouteRoute = AuthenticatedWWsIdRouteRouteImport.update({
  id: '/w/$wsId',
  path: '/w/$wsId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWWsIdIndexRoute = AuthenticatedWWsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedWWsIdRouteRoute,
} as any)
const AuthenticatedWWsIdSettingsRoute =
  AuthenticatedWWsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWsIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdRouteRoute =
  AuthenticatedWWsIdPProjectIdRouteRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => AuthenticatedWWsIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdIndexRoute =
  AuthenticatedWWsIdPProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdIssuesRoute =
  AuthenticatedWWsIdPProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdTaxonomyRoute =
  AuthenticatedWWsIdPProjectIdTaxonomyRouteImport.update({
    id: '/taxonomy',
    path: '/taxonomy',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteImport.update({
    id: '/qa/$stageSlug',
    path: '/qa/$stageSlug',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteImport.update({
    id: '/$roundId',
    path: '/$roundId',
    getParentRoute: () => AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute,
  } as any)
const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteImport.update(
    {
      id: '/$sessionId',
      path: '/$sessionId',
      getParentRoute: () =>
        AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute,
    } as any,
  )
const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute,
    } as any,
  )
const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRouteImport.update(
    {
      id: '/$itemId',
      path: '/$itemId',
      getParentRoute: () =>
        AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/share/$token': typeof ShareTokenRoute
  '/w/$wsId': typeof AuthenticatedWWsIdRouteRouteWithChildren
  '/w/$wsId/settings': typeof AuthenticatedWWsIdSettingsRoute
  '/w/$wsId/': typeof AuthenticatedWWsIdIndexRoute
  '/w/$wsId/p/$projectId': typeof AuthenticatedWWsIdPProjectIdRouteRouteWithChildren
  '/w/$wsId/p/$projectId/issues': typeof AuthenticatedWWsIdPProjectIdIssuesRoute
  '/w/$wsId/p/$projectId/taxonomy': typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  '/w/$wsId/p/$projectId/': typeof AuthenticatedWWsIdPProjectIdIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteWithChildren
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteWithChildren
  '/w/$wsId/p/$projectId/qa/$stageSlug/': typeof AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteWithChildren
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/share/$token': typeof ShareTokenRoute
  '/w/$wsId/settings': typeof AuthenticatedWWsIdSettingsRoute
  '/w/$wsId': typeof AuthenticatedWWsIdIndexRoute
  '/w/$wsId/p/$projectId/issues': typeof AuthenticatedWWsIdPProjectIdIssuesRoute
  '/w/$wsId/p/$projectId/taxonomy': typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  '/w/$wsId/p/$projectId': typeof AuthenticatedWWsIdPProjectIdIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug': typeof AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute
  '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/w/$wsId': typeof AuthenticatedWWsIdRouteRouteWithChildren
  '/_authenticated/w/$wsId/settings': typeof AuthenticatedWWsIdSettingsRoute
  '/_authenticated/w/$wsId/': typeof AuthenticatedWWsIdIndexRoute
  '/_authenticated/w/$wsId/p/$projectId': typeof AuthenticatedWWsIdPProjectIdRouteRouteWithChildren
  '/_authenticated/w/$wsId/p/$projectId/issues': typeof AuthenticatedWWsIdPProjectIdIssuesRoute
  '/_authenticated/w/$wsId/p/$projectId/taxonomy': typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  '/_authenticated/w/$wsId/p/$projectId/': typeof AuthenticatedWWsIdPProjectIdIndexRoute
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteWithChildren
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteWithChildren
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/': typeof AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteWithChildren
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute
  '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/': typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/workspaces'
    | '/share/$token'
    | '/w/$wsId'
    | '/w/$wsId/settings'
    | '/w/$wsId/'
    | '/w/$wsId/p/$projectId'
    | '/w/$wsId/p/$projectId/issues'
    | '/w/$wsId/p/$projectId/taxonomy'
    | '/w/$wsId/p/$projectId/'
    | '/w/$wsId/p/$projectId/qa/$stageSlug'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/workspaces'
    | '/share/$token'
    | '/w/$wsId/settings'
    | '/w/$wsId'
    | '/w/$wsId/p/$projectId/issues'
    | '/w/$wsId/p/$projectId/taxonomy'
    | '/w/$wsId/p/$projectId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId'
    | '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/workspaces'
    | '/share/$token'
    | '/_authenticated/w/$wsId'
    | '/_authenticated/w/$wsId/settings'
    | '/_authenticated/w/$wsId/'
    | '/_authenticated/w/$wsId/p/$projectId'
    | '/_authenticated/w/$wsId/p/$projectId/issues'
    | '/_authenticated/w/$wsId/p/$projectId/taxonomy'
    | '/_authenticated/w/$wsId/p/$projectId/'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId'
    | '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/w/$wsId': {
      id: '/_authenticated/w/$wsId'
      path: '/w/$wsId'
      fullPath: '/w/$wsId'
      preLoaderRoute: typeof AuthenticatedWWsIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/w/$wsId/': {
      id: '/_authenticated/w/$wsId/'
      path: '/'
      fullPath: '/w/$wsId/'
      preLoaderRoute: typeof AuthenticatedWWsIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdRouteRoute
    }
    '/_authenticated/w/$wsId/settings': {
      id: '/_authenticated/w/$wsId/settings'
      path: '/settings'
      fullPath: '/w/$wsId/settings'
      preLoaderRoute: typeof AuthenticatedWWsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWWsIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId': {
      id: '/_authenticated/w/$wsId/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/w/$wsId/p/$projectId'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedWWsIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/': {
      id: '/_authenticated/w/$wsId/p/$projectId/'
      path: '/'
      fullPath: '/w/$wsId/p/$projectId/'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/issues': {
      id: '/_authenticated/w/$wsId/p/$projectId/issues'
      path: '/issues'
      fullPath: '/w/$wsId/p/$projectId/issues'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdIssuesRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/taxonomy': {
      id: '/_authenticated/w/$wsId/p/$projectId/taxonomy'
      path: '/taxonomy'
      fullPath: '/w/$wsId/p/$projectId/taxonomy'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdTaxonomyRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug'
      path: '/qa/$stageSlug'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/'
      path: '/'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug/'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId'
      path: '/$roundId'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/'
      path: '/'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId'
      path: '/$sessionId'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/'
      path: '/'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute
    }
    '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId': {
      id: '/_authenticated/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId'
      path: '/$itemId'
      fullPath: '/w/$wsId/p/$projectId/qa/$stageSlug/$roundId/$sessionId/$itemId'
      preLoaderRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRouteImport
      parentRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute
    }
  }
}

interface AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteChildren {
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute
}

const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteChildren: AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteChildren =
  {
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdItemIdRoute,
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdIndexRoute,
  }

const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteWithChildren =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute._addFileChildren(
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteChildren,
  )

interface AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteChildren {
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteWithChildren
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute
}

const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteChildren: AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteChildren =
  {
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdSessionIdRouteRouteWithChildren,
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdIndexRoute,
  }

const AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteWithChildren =
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute._addFileChildren(
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteChildren,
  )

interface AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteChildren {
  AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteWithChildren
  AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute
}

const AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteChildren: AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteChildren =
  {
    AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRoundIdRouteRouteWithChildren,
    AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugIndexRoute,
  }

const AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteWithChildren =
  AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute._addFileChildren(
    AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteChildren,
  )

interface AuthenticatedWWsIdPProjectIdRouteRouteChildren {
  AuthenticatedWWsIdPProjectIdIssuesRoute: typeof AuthenticatedWWsIdPProjectIdIssuesRoute
  AuthenticatedWWsIdPProjectIdTaxonomyRoute: typeof AuthenticatedWWsIdPProjectIdTaxonomyRoute
  AuthenticatedWWsIdPProjectIdIndexRoute: typeof AuthenticatedWWsIdPProjectIdIndexRoute
  AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute: typeof AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteWithChildren
}

const AuthenticatedWWsIdPProjectIdRouteRouteChildren: AuthenticatedWWsIdPProjectIdRouteRouteChildren =
  {
    AuthenticatedWWsIdPProjectIdIssuesRoute:
      AuthenticatedWWsIdPProjectIdIssuesRoute,
    AuthenticatedWWsIdPProjectIdTaxonomyRoute:
      AuthenticatedWWsIdPProjectIdTaxonomyRoute,
    AuthenticatedWWsIdPProjectIdIndexRoute:
      AuthenticatedWWsIdPProjectIdIndexRoute,
    AuthenticatedWWsIdPProjectIdQaStageSlugRouteRoute:
      AuthenticatedWWsIdPProjectIdQaStageSlugRouteRouteWithChildren,
  }

const AuthenticatedWWsIdPProjectIdRouteRouteWithChildren =
  AuthenticatedWWsIdPProjectIdRouteRoute._addFileChildren(
    AuthenticatedWWsIdPProjectIdRouteRouteChildren,
  )

interface AuthenticatedWWsIdRouteRouteChildren {
  AuthenticatedWWsIdSettingsRoute: typeof AuthenticatedWWsIdSettingsRoute
  AuthenticatedWWsIdIndexRoute: typeof AuthenticatedWWsIdIndexRoute
  AuthenticatedWWsIdPProjectIdRouteRoute: typeof AuthenticatedWWsIdPProjectIdRouteRouteWithChildren
}

const AuthenticatedWWsIdRouteRouteChildren: AuthenticatedWWsIdRouteRouteChildren =
  {
    AuthenticatedWWsIdSettingsRoute: AuthenticatedWWsIdSettingsRoute,
    AuthenticatedWWsIdIndexRoute: AuthenticatedWWsIdIndexRoute,
    AuthenticatedWWsIdPProjectIdRouteRoute:
      AuthenticatedWWsIdPProjectIdRouteRouteWithChildren,
  }

const AuthenticatedWWsIdRouteRouteWithChildren =
  AuthenticatedWWsIdRouteRoute._addFileChildren(
    AuthenticatedWWsIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedWWsIdRouteRoute: typeof AuthenticatedWWsIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedWWsIdRouteRoute: AuthenticatedWWsIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
